name: amss_env
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - alsa-lib=1.2.14=h5eee18b_0
  - attr=2.5.2=h39aace5_0
  - binutils_impl_linux-64=2.44=h4b9a079_2
  - binutils_linux-64=2.44=hc03a8fd_2
  - blas=1.0=openblas
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cairo=1.18.4=h44eff21_0
  - contourpy=1.3.1=py310hdb19cb5_0
  - cycler=0.12.1=py310h06a4308_0
  - cyrus-sasl=2.1.28=h1110e0f_3
  - dbus=1.16.2=h5bd4931_0
  - expat=2.7.3=h7354ed3_4
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - fonttools=4.61.0=py310h47b2149_0
  - freetype=2.14.1=hf5b9546_0
  - gcc_impl_linux-64=15.2.0=hcacfade_7
  - gcc_linux-64=15.2.0=h862fb80_17
  - gettext=0.25.1=h3f43e3d_1
  - gettext-tools=0.25.1=h3f43e3d_1
  - gfortran_impl_linux-64=15.2.0=h281d09f_16
  - gfortran_linux-64=15.2.0=h4f77145_17
  - glib=2.86.3=h617169b_0
  - glib-tools=2.86.3=h9fad118_0
  - graphite2=1.3.14=h295c915_1
  - gst-plugins-base=1.24.11=h651a532_0
  - gstreamer=1.24.11=hc37bda9_0
  - gxx_impl_linux-64=15.2.0=h54ccb8d_7
  - gxx_linux-64=15.2.0=h2d7d49d_17
  - harfbuzz=12.2.0=h15599e2_0
  - icu=75.1=he02047a_0
  - kernel-headers_linux-64=6.12.0=he073ed8_5
  - kiwisolver=1.4.9=py310h24d9097_0
  - krb5=1.21.3=h723845a_4
  - lame=3.100=hbd0596d_1
  - lcms2=2.18=h0c24ade_0
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h6a678d5_0
  - libasprintf=0.25.1=h3f43e3d_1
  - libasprintf-devel=0.25.1=h3f43e3d_1
  - libcap=2.77=h3ff7636_0
  - libclang-cpp21.1=21.1.8=default_h05d3d09_0
  - libclang13=21.1.8=default_hb7eddd9_0
  - libcups=2.3.3=hb8b1518_5
  - libdeflate=1.25=h17f619e_0
  - libdrm=2.4.125=hb03c661_1
  - libedit=3.1.20230828=h5eee18b_0
  - libegl=1.7.0=h5eee18b_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.3=h7354ed3_4
  - libfabric=2.4.0=ha770c72_1
  - libfabric1=2.4.0=h8f87c3e_1
  - libffi=3.4.4=h6a678d5_1
  - libflac=1.5.0=hb705b29_1
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=h69a1729_7
  - libgcc-devel_linux-64=15.2.0=h73f6952_107
  - libgcc-ng=15.2.0=h166f726_7
  - libgettextpo=0.25.1=h3f43e3d_1
  - libgettextpo-devel=0.25.1=h3f43e3d_1
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran-ng=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libgl=1.7.0=h5eee18b_2
  - libglib=2.86.3=h8b17d9a_0
  - libglvnd=1.7.0=h5eee18b_2
  - libglx=1.7.0=h5eee18b_2
  - libgomp=15.2.0=h4751f2c_7
  - libhwloc=2.12.2=default_hafda6a7_1000
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.3=h47b2149_0
  - libkrb5=1.21.3=h520c7b4_4
  - libllvm21=21.1.8=hf7376ad_0
  - liblzma=5.8.2=hb03c661_0
  - liblzma-devel=5.8.2=hb03c661_0
  - libnl=3.11.0=hb9d3cd8_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libogg=1.3.5=h27cfd23_1
  - libopenblas=0.3.30=h46f56fc_2
  - libopengl=1.7.0=h5eee18b_2
  - libopenjpeg=2.5.4=hee96239_1
  - libopus=1.6.1=h9f10d21_0
  - libpciaccess=0.18=h5eee18b_0
  - libpmix=5.0.8=h9b03745_3
  - libpng=1.6.54=hee55ce4_0
  - libpq=18.1=h5c52fec_2
  - libsanitizer=15.2.0=hb13aed2_7
  - libsndfile=1.2.2=hc7d488a_2
  - libsodium=1.0.20=heac8642_0
  - libsqlite=3.51.2=h0c1763c_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-devel_linux-64=15.2.0=h73f6952_107
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libsystemd0=258.3=h6569c3e_0
  - libtiff=4.7.1=h9d88235_1
  - libudev1=258.3=h6569c3e_0
  - libuuid=2.41.3=h5347b49_0
  - libvorbis=1.3.7=h536e056_1
  - libwebp-base=1.6.0=hb7bb969_0
  - libxcb=1.17.0=h9b100fa_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.13.1=hca5e8e5_0
  - libxml2=2.15.1=h26afc86_0
  - libxml2-16=2.15.1=ha9997c6_0
  - libzlib=1.3.1=hb25bd0a_0
  - lmdb=0.9.31=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - matplotlib=3.10.8=py310h06a4308_0
  - matplotlib-base=3.10.8=py310h8a257da_0
  - mpg123=1.32.9=hc50e24c_0
  - mpi=1.0.1=openmpi
  - ncurses=6.5=h7934f7d_0
  - nspr=4.37=h8459abe_0
  - nss=3.117=h3135ca0_0
  - numpy=2.2.5=py310hc213724_2
  - numpy-base=2.2.5=py310hf387b04_2
  - openjpeg=2.5.4=h4e0627c_1
  - openldap=2.6.10=he9288cc_1
  - openmpi=5.0.8=h611b0e2_111
  - openssl=3.6.1=h35e630c_1
  - packaging=25.0=py310h06a4308_1
  - pcre2=10.46=hf426167_0
  - pillow=12.1.0=py310h5a73078_0
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h7934f7d_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pulseaudio-client=17.0=h9a6aba3_3
  - pyparsing=3.2.5=py310h06a4308_0
  - pyqt=5.15.11=py310h144e999_0
  - pyqt5-sip=12.17.0=py310hee96239_0
  - python=3.10.19=h3c07f61_3_cpython
  - python-dateutil=2.9.0post0=py310h06a4308_2
  - python_abi=3.10=3_cp310
  - qt-main=5.15.15=h3c3fd16_6
  - rdma-core=61.0=h192683f_0
  - readline=8.3=hc2a1206_0
  - scipy=1.15.3=py310ha592af2_1
  - setuptools=80.10.1=py310h06a4308_0
  - sip=6.12.0=py310h7934f7d_0
  - six=1.17.0=py310h06a4308_0
  - sqlite=3.51.1=he0a8d7e_0
  - sysroot_linux-64=2.39=hc4b9eeb_5
  - tk=8.6.15=h54e0aa7_0
  - tomli=2.4.0=py310h06a4308_0
  - tornado=6.5.4=py310h47b2149_0
  - tzdata=2025c=he532380_0
  - ucc=1.6.0=hcedbda0_2
  - ucx=1.20.0=hf72d326_1
  - wheel=0.46.3=py310h06a4308_0
  - xcb-util=0.4.1=h5eee18b_2
  - xcb-util-image=0.4.0=h5eee18b_2
  - xcb-util-keysyms=0.4.1=h5eee18b_0
  - xcb-util-renderutil=0.3.10=h5eee18b_0
  - xcb-util-wm=0.4.2=h5eee18b_0
  - xkeyboard-config=2.44=h382ed1a_1
  - xorg-libice=1.1.2=h9b100fa_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxcomposite=0.4.6=h9b100fa_2
  - xorg-libxdamage=1.1.6=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxfixes=6.0.1=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-libxshmfence=1.3.3=h9b100fa_0
  - xorg-libxxf86vm=1.1.6=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.8.2=ha02ee65_0
  - xz-gpl-tools=5.8.2=ha02ee65_0
  - xz-tools=5.8.2=hb03c661_0
  - zlib=1.3.1=hb25bd0a_0
  - zlib-ng=2.3.2=hceb46e0_1
  - zstd=1.5.7=h11fc155_0
prefix: /home/ASC1606/miniconda3/envs/amss_env
